# Generated by Django 5.2.5 on 2025-08-13 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('preferred_tone', models.CharField(choices=[('Formal', 'Formal'), ('Friendly', 'Friendly'), ('Bold', 'Bold')], default='Formal', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Upwork', 'Upwork'), ('Fiverr', 'Fiverr'), ('LinkedIn', 'LinkedIn'), ('Generic', 'Generic')], default='Generic', max_length=20)),
                ('tone', models.CharField(choices=[('Formal', 'Formal'), ('Friendly', 'Friendly'), ('Bold', 'Bold')], default='Formal', max_length=20)),
                ('job_desc', models.TextField(blank=True)),
                ('proposal', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
