# Generated by Django 5.2.5 on 2025-08-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='job_desc',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='proposal',
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proposal',
            name='job_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_text',
            field=models.TextField(default='Sorry!something went wrong.'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='platform',
            field=models.CharField(choices=[('Upwork', 'Upwork'), ('Fiverr', 'Fiverr'), ('LinkedIn', 'LinkedIn'), ('Generic', 'Generic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='tone',
            field=models.CharField(choices=[('Formal', 'Formal'), ('Friendly', 'Friendly'), ('Bold', 'Bold')], max_length=20),
        ),
    ]
