# Generated by Django 5.2.5 on 2025-08-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_remove_proposal_job_desc_remove_proposal_proposal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='confidence',
            field=models.CharField(blank=True, choices=[('green', 'Green - Very Confident'), ('orange', 'Orange - Somewhat Doubtful'), ('red', 'Red - No Chance')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proposal',
            name='outcome',
            field=models.CharField(blank=True, choices=[('green', 'Green - Very Confident'), ('orange', 'Orange - Somewhat Doubtful'), ('red', 'Red - No Chance')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('won', 'Won'), ('lost', 'Lost')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='job_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='platform',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='tone',
            field=models.CharField(max_length=20),
        ),
    ]
