# Generated by Django 5.2.5 on 2025-08-15 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_proposal_confidence_proposal_note_proposal_outcome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='outcome',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='confidence',
            field=models.CharField(choices=[('Green', 'High Confidence'), ('Orange', 'Medium Confidence'), ('Red', 'Low Confidence')], default='Orange', max_length=10),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='platform',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Won', 'Won'), ('Lost', 'Lost')], default='Draft', max_length=10),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_by_client', models.BooleanField(default=False)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='proposals.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received')], default='Pending', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='proposals.proposal')),
            ],
        ),
    ]
