# Generated by Django 5.2.5 on 2025-08-16 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_client_proposal_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerDirectoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=False)),
                ('display_name', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('tagline', models.CharField(blank=True, max_length=150)),
                ('skills', models.TextField(help_text='Comma-separated list of skills')),
                ('qualifications', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('portfolio_link', models.URLField(blank=True)),
                ('projects_completed', models.PositiveIntegerField(default=0)),
                ('testimonials', models.TextField(blank=True)),
                ('preferred_platforms', models.CharField(blank=True, max_length=200)),
                ('preferred_tone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='directory_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
