# Generated by Django 5.2.5 on 2025-08-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_freelancerdirectoryprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelancerdirectoryprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='freelancer_photos/'),
        ),
    ]
