# Generated by Django 5.2.5 on 2025-08-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_payment_is_primary_proposal_last_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerdirectoryprofile',
            name='profession',
            field=models.CharField(blank=True, choices=[('corporate_lawyer', 'Corporate Lawyer'), ('family_lawyer', 'Family Lawyer'), ('criminal_lawyer', 'Criminal Lawyer'), ('intellectual_property_lawyer', 'Intellectual Property Lawyer'), ('tax_lawyer', 'Tax Lawyer'), ('immigration_lawyer', 'Immigration Lawyer'), ('software_developer', 'Software Developer'), ('web_developer', 'Web Developer'), ('mobile_app_developer', 'Mobile App Developer'), ('data_scientist', 'Data Scientist'), ('machine_learning_engineer', 'Machine Learning Engineer'), ('cloud_engineer', 'Cloud Engineer'), ('cybersecurity_specialist', 'Cybersecurity Specialist'), ('devops_engineer', 'DevOps Engineer'), ('ux_designer', 'UX / UI Designer'), ('graphic_designer', 'Graphic Designer'), ('product_designer', 'Product Designer'), ('video_editor', 'Video Editor'), ('animator', 'Animator / Motion Graphics'), ('photographer', 'Photographer'), ('illustrator', 'Illustrator'), ('social_media_manager', 'Social Media Manager'), ('seo_specialist', 'SEO Specialist'), ('digital_marketer', 'Digital Marketer'), ('ppc_specialist', 'PPC / Ads Specialist'), ('brand_strategist', 'Brand Strategist'), ('sales_consultant', 'Sales Consultant'), ('content_writer', 'Content Writer'), ('copywriter', 'Copywriter'), ('technical_writer', 'Technical Writer'), ('journalist', 'Journalist'), ('translator', 'Translator'), ('editor_proofreader', 'Editor / Proofreader'), ('accountant', 'Accountant'), ('financial_analyst', 'Financial Analyst'), ('business_consultant', 'Business Consultant'), ('management_consultant', 'Management Consultant'), ('tax_consultant', 'Tax Consultant'), ('virtual_assistant', 'Virtual Assistant'), ('project_manager', 'Project Manager'), ('tutor', 'Tutor / Educator'), ('corporate_trainer', 'Corporate Trainer'), ('language_instructor', 'Language Instructor'), ('career_coach', 'Career Coach'), ('medical_writer', 'Medical Writer'), ('health_consultant', 'Health Consultant'), ('fitness_trainer', 'Fitness Trainer'), ('nutritionist', 'Nutritionist')], max_length=100),
        ),
    ]
