# Generated by Django 5.2.5 on 2025-08-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_freelancerdirectoryprofile_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerdirectoryprofile',
            name='profession',
            field=models.CharField(choices=[('corporate_lawyer', 'Corporate Lawyer'), ('family_lawyer', 'Family Lawyer'), ('criminal_lawyer', 'Criminal Lawyer'), ('intellectual_property_lawyer', 'Intellectual Property Lawyer'), ('tax_lawyer', 'Tax Lawyer'), ('immigration_lawyer', 'Immigration Lawyer'), ('software_developer', 'Software Developer'), ('web_developer', 'Web Developer'), ('mobile_app_developer', 'Mobile App Developer'), ('data_scientist', 'Data Scientist'), ('machine_learning_engineer', 'Machine Learning Engineer'), ('ux_designer', 'UX / UI Designer'), ('graphic_designer', 'Graphic Designer'), ('video_editor', 'Video Editor'), ('social_media_manager', 'Social Media Manager'), ('seo_specialist', 'SEO Specialist'), ('content_writer', 'Content Writer'), ('copywriter', 'Copywriter'), ('accountant', 'Accountant'), ('business_consultant', 'Business Consultant'), ('tutor', 'Tutor / Educator'), ('fitness_trainer', 'Fitness Trainer'), ('nutritionist', 'Nutritionist'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
