# Generated by Django 5.2.5 on 2025-08-28 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_alter_freelancerdirectoryprofile_profession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='freelancerdirectoryprofile',
            name='profession',
            field=models.CharField(choices=[('Law', [('corporate_lawyer', 'Corporate Lawyer'), ('criminal_lawyer', 'Criminal Lawyer'), ('family_lawyer', 'Family Lawyer'), ('immigration_lawyer', 'Immigration Lawyer'), ('intellectual_property_lawyer', 'Intellectual Property Lawyer'), ('tax_lawyer', 'Tax Lawyer')]), ('Tech', [('data_scientist', 'Data Scientist'), ('machine_learning_engineer', 'Machine Learning Engineer'), ('mobile_app_developer', 'Mobile App Developer'), ('software_developer', 'Software Developer'), ('web_developer', 'Web Developer')]), ('Design', [('graphic_designer', 'Graphic Designer'), ('ux_designer', 'UX / UI Designer'), ('video_editor', 'Video Editor')]), ('Marketing', [('seo_specialist', 'SEO Specialist'), ('social_media_manager', 'Social Media Manager')]), ('Writing', [('content_writer', 'Content Writer'), ('copywriter', 'Copywriter')]), ('Business', [('accountant', 'Accountant'), ('business_consultant', 'Business Consultant')]), ('Education', [('tutor', 'Tutor / Educator')]), ('Health & Wellness', [('fitness_trainer', 'Fitness Trainer'), ('nutritionist', 'Nutritionist')]), ('Other', [('other', 'Other')])], default='other', max_length=100),
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Positive for credit, negative for deduction')),
                ('reason', models.CharField(choices=[('manual_topup', 'Manual Top-up'), ('voucher', 'Voucher Redeem'), ('generation', 'AI Generation Charge'), ('refund', 'Refund'), ('admin_adjust', 'Admin Adjust')], max_length=30)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('other', 'Other / NA')], default='other', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('balance_after', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin/staff who performed the action; null for system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
