# Generated by Django 5.2.5 on 2025-08-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0011_creditrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='confidence',
            field=models.CharField(choices=[('High', 'High Confidence'), ('Medium', 'Medium Confidence'), ('Low', 'Low Confidence')], default='Medium', max_length=10),
        ),
    ]
