# Generated by Django 5.2.5 on 2025-08-29 12:44

import proposals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0012_alter_proposal_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerdirectoryprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='freelancer_photos/', validators=[proposals.models.validate_image_size]),
        ),
    ]
