# Generated by Django 5.2.5 on 2025-08-31 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_alter_freelancerdirectoryprofile_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('freelancer', 'Freelancer'), ('client', 'Client')], max_length=50)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='proposals.proposal')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
