# Generated by Django 5.2.5 on 2025-09-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0014_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='job_title',
            field=models.CharField(default='Untitled Proposal', max_length=200),
        ),
    ]
