# Generated by Django 5.2.5 on 2025-09-01 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0015_proposal_job_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('platform', models.CharField(blank=True, help_text='Upwork, Fiverr, LinkedIn, etc.', max_length=50)),
                ('status_filter', models.CharField(blank=True, help_text='Won, Lost, or All', max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending (Awaiting Payment)'), ('Processing', 'Processing'), ('Ready', 'Ready'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('generated_report', models.FileField(blank=True, null=True, upload_to='progress_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes or comments.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
