# Generated by Django 5.2.5 on 2025-09-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0016_progressreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (Awaiting Payment)'), ('processing', 'Processing'), ('ready', 'Ready'), ('rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
